name: Update Design Tokens

on:
  repository_dispatch:
    types: [update-tokens]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Save tokens (pretty JSON)
      - name: Save tokens file
        run: |
          echo '${{ github.event.client_payload.tokens }}' | jq . > design-tokens.json

      # 3. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 4. Install Style Dictionary (remote, no local setup needed)
      - name: Install Style Dictionary
        run: npm install style-dictionary

      # 5. Build CSS variables
      - name: Build CSS tokens
        run: npx style-dictionary build

      # 6. Commit changes on a new branch
      - name: Commit changes
        run: |
          BRANCH="update-tokens-${{ github.run_id }}"
          git checkout -b $BRANCH
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add design-tokens.json build/css/variables.css
          git commit -m "${{ github.event.client_payload.commitMessage || 'Update design tokens' }}" || echo "No changes to commit"
          git push origin $BRANCH

      # 7. Open a Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ github.event.client_payload.commitMessage || 'Update design tokens' }}
          branch: ${{ github.run_id }}
          title: ${{ github.event.client_payload.commitMessage || 'Update design tokens' }}
          body: "This PR updates the design tokens and generated CSS from the Figma Design Tokens plugin."
          base: main
