name: Update Design Tokens

on:
  repository_dispatch:
    types: 
      - qclgu_design_tokens
      - mandalgu_design_tokens
      - paranaquelgu_design_tokens
      - cgtlgu_design_tokens
      - sjdmlgu_design_tokens

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update Design Tokens
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Save tokens (pretty JSON)
      - name: Save tokens file
        run: |
          mkdir -p ${{ github.event.action }}
          echo '${{ github.event.client_payload.tokens }}' | jq . > ${{ github.event.action }}/${{ github.event.action }}.json

      # 3. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 4. Install Style Dictionary (local only, won't be committed)
      - name: Install Style Dictionary
        run: npm install --no-save style-dictionary

      # 4.55 Optional: convert numbers to px
      - name: Append px to numeric values
        run: |
          jq 'walk(
                if type=="number" then tostring + "px" else . end
              )' ${{ github.event.action }}/${{ github.event.action }}.json > tmp.json && mv tmp.json ${{ github.event.action }}/${{ github.event.action }}.json
              
      # 4.6 Create dynamic Style Dictionary config
      - name: Create dynamic Style Dictionary config
        run: |
          cat > style-dictionary.config.json <<EOL
          {
            "source": ["${{ github.event.action }}/${{ github.event.action }}.json"],
            "platforms": {
              "css": {
                "transformGroup": "css",
                "buildPath": "${{ github.event.action }}/",
                "transforms": ["attribute/cti", "name/kebab"],
                "files": [
                  {
                    "destination": "${{ github.event.action }}.css",
                    "format": "css/variables",
                    "options": { "outputReferences": true }
                  }
                ]
              }
            }
          }
          EOL
    
      # 5. Build CSS variables
      - name: Build CSS tokens
        run: npx style-dictionary build --config style-dictionary.config.json --verbose

      # 5b. Clean up node_modules and lockfiles
      - name: Clean up node_modules
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      # Commit and create PR (only JSON + CSS)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ github.event.client_payload.commitMessage || format('Update {0}', github.event.action) }}
          branch: ${{ github.event.action }}_${{ github.run_id }}
          title: ${{ github.event.client_payload.commitMessage || format('Update {0}', github.event.action) }}
          body: "This PR updates the design tokens and generated CSS from the Figma Design Tokens plugin."
          base: main
          add-paths: |
            ${{ github.event.action }}/${{ github.event.action }}.json
            ${{ github.event.action }}/${{ github.event.action }}.css
