name: Update Design Tokens

on:
  repository_dispatch:
    types: [update-tokens]
    
permissions:
  contents: write
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Save tokens file
        run: |
          echo '${{ github.event.client_payload.tokens }}' | jq . > design-tokens.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add design-tokens.json
          git commit -m "${{ github.event.client_payload.commitMessage }}" || echo "Update design tokens"
          git push
